services:
  netra-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev

    env_file:
      - .env.local

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

    environment:
      - WATCHPACK_POLLING=true